---
title: "history"
format: html
editor: visual
---

## git init

git add Readme.md

git commit -m "commit"

git branch -M main

git remote set-url origin git\@github

.com:hsteini/ML.git

ssh -T git\@github.com

git push -u origin main

# Timeline

1950 Alan Turing "Computing Machinery and Intelligence", darin stellt er die Frage "Can machines think?".

The Turing Test: Can a machine exhibit intelligent behavior indistinguishable from that of a human? The Turing Test has become a central concept in AI, serving as one way to measure machine intelligence by assessing a machine's ability to convincingly mimic human conversation and behavior.

1951 Marvin Minsky und Dean Edmunds bauen das erste artificial neural network

1955 findet der berühmte Workshop "A Proposal for the Dartmouth Summer Research Project on Artificial Intelligence" in Dartmouth statt. Und John McCarthy verwendet erstmals den Ausdruck "artificial intelligence". Teilnehmer sind auch Marvin Minsky aus Harvard, Nathaniel Rochester von IBM und Claude Shannon von Bell Telephone Laboratories.
